AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for cross-account access to Health Events

Parameters:
  DataCollectionAccountID:
    Type: String
    Description: "The AWS Account ID of the Data Collection Account"
  ManagementAccountRoleName:
    Type: String
    Default: "DataCollectionCrossAccountRole"
    Description: "The name of the IAM role to be created for the management account"
  DataCollectionLambdaRoleArn:
    Type: String
    Description: "The ARN of the IAM role for Lambda in the data collection account"

Resources:
  CrossAccountRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref ManagementAccountRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Ref DataCollectionAccountID
                - !Ref DataCollectionLambdaRoleArn  # 这里引用完整的 ARN
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "HealthEventsAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "health:DescribeEvents"
                  - "health:DescribeEventDetails"
                  - "health:DescribeAffectedEntities"
                Resource: "*"
        - PolicyName: "OrganizationsAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "organizations:ListAccountsForParent"
                  - "organizations:DescribeAccount"
                  - "organizations:ListParents"
                  - "organizations:ListRoots"
                  - "organizations:ListChildren"
                  - "organizations:ListTagsForResource"
                  - "organizations:ListAccounts"
                  - "organizations:DescribeOrganizationalUnit"
                  - "organizations:ListCreateAccountStatus"
                  - "organizations:DescribeOrganization"
                  - "organizations:ListOrganizationalUnitsForParent"
                Resource: "*"