
NAME_PREFIX = 'AwsHealthDashboard'

LAMBDA_ROLE = f'{NAME_PREFIX}LambdaRole'

ACCOUNTS_TABLE_NAME = f'{NAME_PREFIX}ManagementAccounts'
USERS_TABLE_NAME = f'{NAME_PREFIX}Users'

HEALTH_EVENTS_TABLE_NAME = f'{NAME_PREFIX}HealthEvents'
EVENT_DETAILS_TABLE_NAME = f'{NAME_PREFIX}EventDetails'
AFFECTED_ACCOUNTS_TABLE_NAME = f'{NAME_PREFIX}AffectedAccounts'
AFFECTED_ENTITIES_TABLE_NAME = f'{NAME_PREFIX}AffectedEntities'